language: python
install: pip install tox
matrix:
  include:
    - python: 2.7
      env:
        - TOX_ENV=py27
    - python: 3.5
      env:
        - TOX_ENV=py35
    - python: 3.7
      env:
        - TOX_ENV=py37
    - python: 3.9
      env:
        - TOX_ENV=py39
script: tox -e $TOX_ENV
